---

- hosts: all
  become: true
  tasks:

  - name: install httpd package
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "Centos"

  - name: install chrony package
    yum:
      name: chrony
      state: present     
    when: ansible_distribution == "Centos"


  
  - name: install apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: install chrony package
    apt:
      name: chrony
      state: present
    when: ansible_distribution == "Ubuntu"

