---

- hosts: all
  become: true
  tasks:

  - name: install httpd and  chrony package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ chrony_package }}"
      state: present



  




