---

- hosts: all
  become: true
  tasks:

  

  - name: install httpd package
    yum:
      name: 
        - httpd
        - chrony
      state: present
    when: ansible_distribution == "Centos"

 
  - name: install httpd package
    apt:
      name: 
        - apache2
        - chrony
      state: present
    when: ansible_distribution == "Ubuntu"



- hosts: Webserver
  become: true
  tasks:


  - name: install mariadb package
    apt:
      name:
        - mariadb-server
        - postfix
      state: present
    when: ansible_distribution == "Ubuntu"

